# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardware.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehardware.proto\x12\x08hardware\"\x11\n\x0fHardwareRequest\";\n\x10HardwareResponse\x12\x11\n\tcpu_usage\x18\x01 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x02 \x01(\x02\x32V\n\x0fHardwareService\x12\x43\n\x08GetUsage\x12\x19.hardware.HardwareRequest\x1a\x1a.hardware.HardwareResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardware_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HARDWAREREQUEST._serialized_start=28
  _HARDWAREREQUEST._serialized_end=45
  _HARDWARERESPONSE._serialized_start=47
  _HARDWARERESPONSE._serialized_end=106
  _HARDWARESERVICE._serialized_start=108
  _HARDWARESERVICE._serialized_end=194
# @@protoc_insertion_point(module_scope)
